import { useEffect, useRef, useState } from 'react';
import { Asset, Button, Intro } from '../components/UI';
import RippleCard from '../components/RippleCard';
import { organization, organizationRipples, statuses, feedbackOptions, applyOrganizationAction } from '../data/organization';
import '../styles/organization.css';

const base = '#/organization';
function ActionDialog({ type, ripple, onClose, onPublish }) {
  const ref = useRef(null);
  const [preview, setPreview] = useState(false);
  const [title, setTitle] = useState('');
  const [message, setMessage] = useState('');
  const [status, setStatus] = useState(ripple.status);
  const [question, setQuestion] = useState(`What would improve your ${ripple.id === 'route-7' ? 'Route 7 experience' : ripple.title.toLowerCase()} most?`);
  const [options, setOptions] = useState(feedbackOptions);
  useEffect(() => { const trigger = document.activeElement; ref.current.showModal(); return () => trigger?.focus(); }, []);
  return <dialog className="org-dialog" ref={ref} onCancel={onClose} aria-labelledby="dialog-title">
    <div className="org-section-heading"><h2 id="dialog-title">{type === 'acknowledge' ? 'Acknowledge this Ripple' : type === 'question' ? 'Ask the community' : 'Publish an update'}</h2><button type="button" onClick={onClose} aria-label="Close dialog">✕</button></div>
    <p>{ripple.title}</p>
    <form onSubmit={e => { e.preventDefault(); if (type === 'question' && !preview) setPreview(true); else onPublish({ type, title, message, status, question, options }); }}>
      {type === 'acknowledge' ? <><blockquote>“We're listening.”</blockquote><p>✓ Organization acknowledged this Ripple<br />{organization.name} is reviewing the community feedback.</p><small>Acknowledgment communicates listening. It does not imply accepting legal responsibility or admitting fault.</small></> : type === 'update' ? <><label>Update title<input required pattern=".*\S.*" maxLength={120} value={title} onChange={e => setTitle(e.target.value)} placeholder="Additional peak-hour service being reviewed" /></label><label>Message<textarea required maxLength={3000} rows={5} value={message} onChange={e => { setMessage(e.target.value); e.target.setCustomValidity(e.target.value.trim() ? "" : "Please enter a message."); }} placeholder="We are reviewing capacity during the morning peak and evaluating additional service." /></label><label>Status<select value={status} onChange={e => setStatus(e.target.value)}>{statuses.map(s => <option key={s}>{s}</option>)}</select></label><small>Resolved means your organization's action is completed. Community reports remain visible.</small></> : preview ? <section className="org-panel"><p className="eyebrow">Community preview</p><p>We'd like to understand this issue better.</p><h3>{question}</h3><ul>{options.map((o, i) => <li key={i}>{o}</li>)}</ul><small>Shared with people following this Ripple in the demo.</small></section> : <><p>We'd like to understand this issue better.</p><label>Question<input required pattern=".*\S.*" maxLength={240} value={question} onChange={e => setQuestion(e.target.value)} /></label><fieldset><legend>Response options</legend>{options.map((o, i) => <label key={i}>Option {i + 1}<input required pattern=".*\S.*" maxLength={100} value={o} onChange={e => setOptions(options.map((v, n) => n === i ? e.target.value : v))} /></label>)}</fieldset></>}
      <div className="org-inline"><Button type="button" secondary onClick={preview ? () => setPreview(false) : onClose}>{preview ? 'Edit question' : 'Cancel'}</Button><Button type="submit">{type === 'question' ? preview ? 'Publish question' : 'Preview question' : type === 'acknowledge' ? 'Publish acknowledgment' : 'Publish update'}</Button></div>
    </form>
  </dialog>;
}
function Progress({ ripple }) {
  const steps = [['Community Ripple detected', true, 'Community activity'], ['Organization acknowledged', ripple.acknowledged, 'Organization update'], ['Community feedback requested', ripple.questions.length > 0, 'Organization update'], ['Action announced', ripple.updates.some(u => ['Action planned', 'In progress', 'Resolved'].includes(u.status)), 'Organization update'], ['In progress', ripple.updates.some(u => ['In progress', 'Resolved'].includes(u.status)), 'Organization update'], ['Resolved', ripple.updates.some(u => u.status === 'Resolved'), 'Organization update']];
  return <ol className="org-timeline">{steps.map(([label, done, source]) => <li key={label} className={done ? 'done' : ''}><span aria-hidden="true">{done ? '✓' : '○'}</span><div><small>{source} · {done ? 'Recorded' : 'Not yet recorded'}</small><h3>{label}</h3>{label === 'Organization acknowledged' && done && <p>{organization.name} is reviewing the community feedback.</p>}</div></li>)}</ol>;
}
function Feedback({ item }) {
  const total = item.results.reduce((a, b) => a + b, 0);
  return <article className="org-panel"><small>Community feedback · {item.date}</small><h3>{item.question}</h3><p>{item.demo ? 'Illustrative demo results' : 'Published in this demo'} · {total} responses</p>{item.options.map((o, i) => <div className="org-result" key={i}><div><span>{o}</span><strong>{total ? Math.round(item.results[i] / total * 100) : 0}%</strong></div><progress value={item.results[i]} max={total || 1} aria-label={o} /></div>)}{!total && <small>Awaiting community feedback. Live responses are not connected.</small>}</article>;
}
export default function Organization({ path }) {
  const [ripples, setRipples] = useState(() => structuredClone(organizationRipples));
  const [claimed, setClaimed] = useState(false);
  const [account, setAccount] = useState(false);
  const [modal, setModal] = useState(null);
  const [notice, setNotice] = useState('');
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('All statuses');
  const [following, setFollowing] = useState([]);
  const section = path.split('/')[2] || 'dashboard';
  const ripple = ripples.find(r => r.id === path.split('/')[3]);
  const publicView = section === 'community';
  const updates = ripples.flatMap(r => r.updates.map(u => ({ ...u, ripple: r })));
  const active = ripples.filter(r => r.status !== 'Resolved').length;
  const stats = [[active, 'Active community Ripples'], [ripples.reduce((n, r) => n + r.voices, 0), 'Community voices'], [ripples.filter(r => !r.acknowledged && !r.updates.length).length, 'Awaiting response'], [updates.length, 'Updates published']];
  function publish(action) { if (applyOrganizationAction(ripple, action) === ripple) return; setRipples(items => items.map(r => r.id === ripple.id ? applyOrganizationAction(r, action) : r)); setModal(null); setNotice('Published in this demo. The community view has been updated.'); }
  return <div className="org-app">
    <header className="org-header"><a className="brand" href={base}><Asset screen="5:1224" name="imgRippleMark" /><span>Ripple</span></a><span className="org-workspace">FOR ORGANIZATIONS</span><a className="org-account" href={`${base}/profile`}><span className="org-avatar">OC</span><span>OC Transpo<small>Community partner</small></span></a></header>
    <div className="org-shell"><aside className="org-sidebar"><p className="eyebrow">Your workspace</p><nav aria-label="Organization navigation">{[['dashboard', 'Community Listening', '◉'], ['ripples', 'Community Ripples', '◎'], ['updates', 'Updates', '↗'], ['profile', 'Organization Profile', '▤']].map(([key, label, icon]) => <a key={key} href={`${base}${key === 'dashboard' ? '' : '/' + key}`} aria-current={section === key ? 'page' : undefined}><span aria-hidden="true">{icon}</span>{label}</a>)}</nav><div className="org-sidebar-note"><Asset screen="5:1224" name="imgRippleMark" /><strong>Better, together.</strong><p>Listen to your community.<br />Move forward together.</p></div><a className="text-link" href="#/">← Citizen home</a></aside>
    <main className="org-main"><div className="org-demo"><span>DEMO WORKSPACE</span> Illustrative data · Session-only actions · Reset when you leave this workspace or reload.</div>
      {notice && <div className="org-notice" role="status">{notice}<button aria-label="Dismiss notification" onClick={() => setNotice('')}>✕</button></div>}
      {['invitation', 'account', 'claim'].includes(section) ? <section className="org-onboarding org-panel"><p className="eyebrow">Community partnership starts here</p><Intro title={section === 'invitation' ? 'Your community is talking. Join the conversation.' : section === 'account' ? 'Welcome to your listening hub.' : 'Claim your organization profile'} />{section === 'invitation' ? <><p>People on Ripple are sharing experiences related to your services. Claim your organization profile to understand recurring community needs, request structured feedback, and keep people informed about the actions you're taking.</p><ul>{['Understand recurring community needs', 'Collect structured feedback', 'Respond directly to emerging concerns', 'Share progress transparently'].map(t => <li key={t}>{t}</li>)}</ul><a className="button" href={`${base}/account`}>Claim organization profile</a><a className="text-link" href="#/how-it-works">Learn how Ripple works</a></> : section === 'account' ? <><p>Create an account or log in to continue. This walkthrough uses a demo account; no credentials are needed.</p><div className="org-inline">{['Create demo account', 'Log in to demo'].map(t => <Button key={t} onClick={() => { setAccount(true); window.location.hash = '/organization/claim'; }}>{t}</Button>)}</div></> : !account ? <a className="button" href={`${base}/account`}>Continue with a demo account</a> : <form onSubmit={e => { e.preventDefault(); setClaimed(true); setNotice('Demo profile claimed. Verification is simulated; no real organization has been verified.'); window.location.hash = '/organization'; }}><h2>OC Transpo</h2><p>Public transportation provider · Ottawa</p><p>In a live workspace, Ripple would verify your authority to represent this organization before granting publishing access.</p><label className="org-checkbox"><input type="checkbox" required /> I understand this is a simulated organization claim.</label><Button type="submit">Verify and claim demo profile</Button></form>}</section> : ripple && ['ripples', 'community'].includes(section) ? <>
        <a className="text-link" href={`${base}/ripples`}>← Community Ripples</a><div className="org-section-heading"><Intro eyebrow={publicView ? 'Community view · Demo' : 'Community Ripple'} title={ripple.title}>{ripple.description}</Intro><span className="status-badge teal">● {ripple.status}</span></div>
        <div className="org-detail-grid"><div><section className="org-panel"><h2>Community signal</h2><div className="org-signal-stats"><div><strong>{ripple.voices}</strong><p>community voices</p></div><div><strong>+{ripple.weekly}</strong><p>this week</p></div></div><p>Most frequently reported: <strong>{ripple.peak}</strong></p><p>Common location/context: <strong>{ripple.context}</strong></p></section><section className="org-panel"><h2>Progress timeline</h2><Progress ripple={ripple} /></section><section className="org-updates"><h2>Official updates</h2>{ripple.updates.length ? ripple.updates.map((u, i) => <article className="org-panel" key={i}><small>Organization update · {organization.name} · {u.date}</small><h3>{u.title}</h3><p>{u.message}</p><span className="status-badge teal">{u.status}</span></article>) : <p>No official updates yet. Follow this Ripple to keep track of progress.</p>}</section><section className="org-updates"><h2>Community feedback</h2>{ripple.questions.length ? ripple.questions.map((q, i) => <Feedback key={i} item={q} />) : <p>No feedback requests yet.</p>}</section></div><aside><section className="org-panel org-actions"><p className="eyebrow">{publicView ? 'Stay connected' : 'A space for constructive dialogue'}</p><h2>{publicView ? 'Follow progress' : 'Organization actions'}</h2>{publicView ? <><p>{organization.name} can share what it is learning and the actions it is taking here.</p><Button aria-pressed={following.includes(ripple.id)} onClick={() => setFollowing(ids => ids.includes(ripple.id) ? ids.filter(id => id !== ripple.id) : [...ids, ripple.id])}>{following.includes(ripple.id) ? 'Following this Ripple' : 'Follow this Ripple'}</Button><small>Following is saved for this demo session. Notifications are not connected.</small></> : <><p>Listen, learn, and keep your community informed.</p><Button secondary disabled={ripple.acknowledged} onClick={() => setModal('acknowledge')}>{ripple.acknowledged ? '✓ Acknowledged' : 'Acknowledge this Ripple'}</Button><Button secondary onClick={() => setModal('question')}>Ask the community</Button><Button onClick={() => setModal('update')}>Publish an update</Button><a className="text-link" href={`${base}/community/${ripple.id}`}>View as a community member ↗</a></>}</section><div className="org-partnership"><h3>Progress starts with listening.</h3><p>Community voices remain visible. Your responses add context and help people follow the work ahead.</p></div></aside></div>
      </> : section === 'profile' ? <><Intro eyebrow="Organization Profile" title="OC Transpo" /><section className="org-panel org-profile"><span className="org-avatar">OC</span><h2>OC Transpo</h2><p>✓ Verified Organization <small>(demo{claimed ? ' · profile claimed' : ''})</small></p><span className="status-badge teal">● Listening on Ripple</span><h3>About</h3><p>{organization.about}</p><h3>Community engagement</h3><div className="org-stats">{[[active, 'active Ripples'], [updates.length, 'official updates'], [ripples.reduce((n, r) => n + r.questions.length, 0), 'feedback requests']].map(([n, t]) => <div key={t}><strong>{n}</strong><p>{t}</p></div>)}</div><a className="button" href={`${base}/ripples`}>View community Ripples</a><a className="text-link" href={`${base}/invitation`}>Explore the invitation & claim walkthrough</a></section></> : section === 'updates' ? <><Intro eyebrow="Keep your community informed" title="Updates">Official updates from your organization, all in one place.</Intro><div className="org-updates">{updates.map((u, i) => <article className="org-panel" key={i}><small>{u.ripple.title} · {u.date}</small><h2>{u.title}</h2><p>{u.message}</p><span className="status-badge teal">{u.status}</span><a className="text-link" href={`${base}/ripples/${u.ripple.id}`}>View Ripple →</a></article>)}</div></> : ['dashboard', 'ripples'].includes(section) && !path.split('/')[3] ? <>
        <Intro eyebrow="Community Listening" title={section === 'dashboard' ? 'Good morning, OC Transpo' : 'Community Ripples'}>Understand what your community is experiencing and keep them informed about what you're doing.</Intro>
        {section === 'dashboard' && <><div className="org-stats">{stats.map(([n, label]) => <article key={label}><span>{label}</span><strong>{n}</strong><small>{label === 'Community voices' ? 'Across these community Ripples' : 'In your demo workspace'}</small></article>)}</div><section className="org-banner"><div><p className="eyebrow">Every voice is a starting point</p><h2>A shared understanding. A step forward.</h2><p>Your community is sharing experiences. You have the tools to listen and respond.</p></div><span className="org-rings" aria-hidden="true"><i /><i /><i /></span></section></>}
        <div className="org-section-heading"><div><h2>Community signals</h2><p>Recurring experiences connected to your services.</p></div><span className="org-count">{ripples.length} Ripples</span></div>
        <div className="org-filters"><label>Search Ripples<input type="search" placeholder="Search by title or location" value={query} onChange={e => setQuery(e.target.value)} /></label><label>Status<select value={filter} onChange={e => setFilter(e.target.value)}>{['All statuses', ...statuses].map(s => <option key={s}>{s}</option>)}</select></label></div>
        <div className="org-card-grid">{ripples.filter(r => `${r.title} ${r.location}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'All statuses' || r.status === filter)).map(r => <RippleCard key={r.id} ripple={{ ...r, tone: 'teal', updated: 'today' }} organizationView />)}</div>{!ripples.some(r => `${r.title} ${r.location}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'All statuses' || r.status === filter)) && <p className="org-panel">No Ripples match these filters. Try another search or status.</p>}
        <footer className="org-footer">Citizens identify patterns. Ripple organizes the signals. Together, we move forward.</footer>
      </> : <section className="org-panel"><Intro title="This Ripple couldn't be found." /><a className="button" href={`${base}/ripples`}>View community Ripples</a></section>}
    </main></div>{modal && ripple && <ActionDialog key={`${ripple.id}-${modal}`} type={modal} ripple={ripple} onClose={() => setModal(null)} onPublish={publish} />}
  </div>;
}
